language: java
# safelist
branches:
  only:
  - master
  - stage
  - develop
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#skolarapp
    on_success: always
    on_failure: always
    use_notice: true
env:
  global:
    - secure: rTG27shLNCaRcVoxvQ5hvinmU+ELPjTR/lj4ESjnOGILIHDXY9wd9tQPWSMkcRviHQ8yd0gs3pDWdRS+rBwgSIZXyImete0GRHZedENilt+YKivPZitdKJUxKw7twD6R/yiATgU6vdn7Xz9lWJ2q+Om57hdk9nzH8m8A9fzBUwxqBbNK6V9asEvVVlla2UkJ6P96ct+zryyXMO5UExtSz97GOWlhnsrsxnWB3ydUJrrWnsNb3NGA6JlEAoYLHsNITDSVX+0zQHIOsDrogTIfHprIZGhszNf+NlN5d9nI7h8BIdUlgEgvKAAg3+WDVqTTRcnyGfzG4OpUdycLK0tdS/XwxmA7OH3VkrVcc4FBvFHIgefauGykJzCPf1eDJZzRm6f6PJv+hJFmwlOb4Ou4OPi4dArYLZ5xhvwyO6R9vb73nv4hA39HSB8VMf2Sm/rz5P9fjPIV0dVUa3FNaOm7qtK7AcjfxYIDSY93yC1tA4MvM2hSyybU65yOKe3BvGzAxgFA5uOrhPviD7XcUPt6qJ+fxb81wdSetU+YjgQwjl4QzLIWEWf4TH7300Dxn+OuT49uaU7v2f+XgyGn5FhxuwVGKPcCG+Ty4GFKF6sSTdQvt6DB0rd2gbxgxXX1NxQRO1DXpUYQRRIpUlmodYeDvpxp1JCbs6XlAPy8sZZ39l0=
os:
  - linux
  #- osx


after_success:
  - ./gradlew stage
  - ./gradlew test

  - chmod a+x automerge
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    echo "Merging develop into stage";
    BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=stage GITHUB_REPO=SkolaRapp/TicTacToe ./automerge;
    echo "All done, quitting now"; exit 0; fi

  - if [ "$TRAVIS_BRANCH" == "stage" ]; then
    echo "Merging stage into master";
    BRANCHES_TO_MERGE_REGEX='stage' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=SkolaRapp/TicTacToe ./automerge; fi

deploy:
  provider: heroku
  api_key:
    secure: 28NVfNmCtg+tFqOGgmuJambp0gOrXybP3yyRk9fw3SrqHgzdVlD+rkuso+eJvNZJonjWbXZz8NQOm1WveRFpA1Ypg5VXY3zEwb2/QtHdYyj60E3/uw3yKNphEUhYb/9lMCb8FwpLRMRbumHhcvCUMykN/IipPqsW/S9sJg1Er8MaBAqabKoDyGVKZ6+IwgSu8eUYUeeavyb29b/SGaMx6qkKF4m19C6jGblLK38ZJjoY9l3gdybebdGaR6HJ7wjQ7K1J1jDRd7X4tRIdETVFP99/EyZ2o2zqf2NXHb1552Z+HxjstnuiPfYtRR72/IPmw6ScAzuJsV/DKdRfSkREvQwOFGSPYg2zaC2LUmJFnMn7Q4JtLCcELr+OebwfyDRABxariTK9xVI9v+IaHpc8OBAZvw4ihqF9WYY0J/M5RxSmnl/hdjL/iZ/n9NfPX9TfIlwEuDphhsmpd2tfwjVwBf+GKfORkaHkh6t7nhziUYUtgrGkVojs26ZOxy+pX4A1qEg5NA1rKxMt6Xkmkmpvvsj2l2ldRvph/F5Pj4mHGzvs1P1Dcn6m+tKJE+yck9gsH5BRD0PnWVGNGkXLz4EZA6IeUN1DCZZ+k+awKwVy+IxLhF9FuKVxqe+jIloqL2ggVKFy7erZjubbY8F0YxOHo+2Ck1wD8MF/Q2WMXekgW30=
  app:
    stage: skolarapp-dev